[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
addopts = "-q --disable-warnings"


[tool.coverage.run]
branch = true
source = ["rag"]
omit = ["**/__init__.py"]

[tool.coverage.report]
skip_empty = true
